ADANIPORTS.NS: Infrastructure
ASIANPAINT.NS: Consumer
AXISBANK.NS: Finance
BAJAJ-AUTO.NS: Automotive
BAJFINANCE.NS: Finance
BAJAJFINSV.NS: Finance
BPCL.NS: Energy
BHARTIARTL.NS: Telecom
BRITANNIA.NS: FMCG
CIPLA.NS: Pharma
COALINDIA.NS: Energy
DIVISLAB.NS: Pharma
DRREDDY.NS: Pharma
EICHERMOT.NS: Automotive
GRASIM.NS: Materials
HCLTECH.NS: Tech
HDFC.NS: Finance
HDFCBANK.NS: Finance
HDFCLIFE.NS: Finance
HEROMOTOCO.NS: Automotive
HINDALCO.NS: Materials
HINDUNILVR.NS: FMCG
ICICIBANK.NS: Finance
INDUSINDBK.NS: Finance
INFY.NS: Tech
IOC.NS: Energy
ITC.NS: FMCG
JSWSTEEL.NS: Materials
KOTAKBANK.NS: Finance
LT.NS: Industrials
M&M.NS: Automotive
MARUTI.NS: Automotive
NESTLEIND.NS: FMCG
NTPC.NS: Utilities
ONGC.NS: Energy
POWERGRID.NS: Utilities
RELIANCE.NS: Energy
SBILIFE.NS: Finance
SBIN.NS: Finance
SHREECEM.NS: Materials
SUNPHARMA.NS: Pharma
TATASTEEL.NS: Materials
TATACONSUM.NS: FMCG
TATAMOTORS.NS: Automotive
TITAN.NS: Consumer
ULTRACEMCO.NS: Materials
UPL.NS: Chemicals
WIPRO.NS: Tech
TECHM.NS: Tech
TCS.NS: Tech
