# Fusion Weights for combining different anomaly scores
fusion_weights:
  alpha: 0.33  # Weight for Sentiment Anomaly Score
  beta: 0.33   # Weight for Statistical Anomaly Score
  gamma: 0.34  # Weight for Deep Anomaly Score

# Anomaly detection thresholds
anomaly_thresholds:
  sentiment_threshold: 0.5  # Sentiment score threshold for anomaly detection
  z_score_threshold: 2.5    # Z-score threshold for statistical anomaly detection
  rsi_threshold: 70         # RSI threshold (overbought/oversold condition)
  
# Deep Anomaly detection parameters
deep_anomaly_params:
  reconstruction_error_threshold: 0.8  # Threshold for reconstruction error in Transformer Autoencoder (TAE)
  anomaly_detection_method: "TAE-GAN"  # Method used for deep anomaly detection (e.g., TAE-GAN)

# Sentiment scoring model weights
sentiment_model_weights:
  finbert_weight: 1.0  # Weight for FinBERT sentiment score
  wcn_weight: 0.5      # Weight for Weighted Category Network (WCN) classification score
